### ISSUE TITLE
Action sheet on iOS 10 not working while using hoko SDK

### ISSUE THREAD

**Issue by pawlowskim** [hoko/hoko-ios#28] opened 2016-10-20 10:39 UTC
Hello,

I'm developer of react native currently. We have faced an issue with new iOS 10. Since we start testing it on the new OS we saw that Action Sheet from iOS is not working - it's not showing. It throws warning with constrains:

```
2016-10-20 12:17:10.617274 oolipo[12227:113297] [LayoutConstraints] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. 
    Try this: 
        (1) look at each constraint and try to figure out which you don't expect; 
        (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x608000281ef0 UIView:0x7fcf29418a10.width == - 20   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x608000281ef0 UIView:0x7fcf29418a10.width == - 20   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-10-20 12:17:10.623462 oolipo[12227:113297] [LayoutConstraints] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. 
    Try this: 
        (1) look at each constraint and try to figure out which you don't expect; 
        (2) find the code that added the unwanted constraint or constraints and fix it. 
    (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x618000283c00 h=--- v=--- UIWindow:0x7fcf29538cd0.height == 0   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x618000285280 h=-&- v=-&- UITransitionView:0x7fcf294448f0.height == UIWindow:0x7fcf29538cd0.height   (active)>",
    "<NSLayoutConstraint:0x6180002841f0 V:|-(>=10)-[_UIAlertControllerView:0x7fcf2943bdf0]   (active, names: '|':UITransitionView:0x7fcf294448f0 )>",
    "<NSLayoutConstraint:0x618000284240 _UIAlertControllerView:0x7fcf2943bdf0.bottom <= UITransitionView:0x7fcf294448f0.bottom - 10   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x618000284240 _UIAlertControllerView:0x7fcf2943bdf0.bottom <= UITransitionView:0x7fcf294448f0.bottom - 10   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-10-20 12:17:10.624014 oolipo[12227:113297] [LayoutConstraints] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. 
    Try this: 
        (1) look at each constraint and try to figure out which you don't expect; 
        (2) find the code that added the unwanted constraint or constraints and fix it. 
    (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x618000283c00 h=--- v=--- UIWindow:0x7fcf29538cd0.height == 0   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x618000285280 h=-&- v=-&- UITransitionView:0x7fcf294448f0.height == UIWindow:0x7fcf29538cd0.height   (active)>",
    "<NSLayoutConstraint:0x60800009ea50 UIView:0x7fcf29418a10.height >= 44   (active)>",
    "<NSLayoutConstraint:0x60800009f0e0 _UIAlertControllerView:0x7fcf2943bdf0.height == UIView:0x7fcf29418a10.height   (active)>",
    "<NSLayoutConstraint:0x6180002841a0 _UIAlertControllerView:0x7fcf2943bdf0.bottom == UITransitionView:0x7fcf294448f0.bottom - 10   (active)>",
    "<NSLayoutConstraint:0x6180002841f0 V:|-(>=10)-[_UIAlertControllerView:0x7fcf2943bdf0]   (active, names: '|':UITransitionView:0x7fcf294448f0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60800009ea50 UIView:0x7fcf29418a10.height >= 44   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-10-20 12:17:10.624488 oolipo[12227:113297] [LayoutConstraints] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. 
    Try this: 
        (1) look at each constraint and try to figure out which you don't expect; 
        (2) find the code that added the unwanted constraint or constraints and fix it. 
    (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x618000283c00 h=--- v=--- UIWindow:0x7fcf29538cd0.height == 0   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x618000285280 h=-&- v=-&- UITransitionView:0x7fcf294448f0.height == UIWindow:0x7fcf29538cd0.height   (active)>",
    "<NSLayoutConstraint:0x60800009ec30 UIView:0x7fcf2943ef30.height <= UIView:0x7fcf29418a10.height   (active)>",
    "<NSLayoutConstraint:0x60800009f0e0 _UIAlertControllerView:0x7fcf2943bdf0.height == UIView:0x7fcf29418a10.height   (active)>",
    "<NSLayoutConstraint:0x6180002841a0 _UIAlertControllerView:0x7fcf2943bdf0.bottom == UITransitionView:0x7fcf294448f0.bottom - 10   (active)>",
    "<NSLayoutConstraint:0x6180002841f0 V:|-(>=10)-[_UIAlertControllerView:0x7fcf2943bdf0]   (active, names: '|':UITransitionView:0x7fcf294448f0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60800009ec30 UIView:0x7fcf2943ef30.height <= UIView:0x7fcf29418a10.height   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-10-20 12:17:10.624949 oolipo[12227:113297] [LayoutConstraints] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. 
    Try this: 
        (1) look at each constraint and try to figure out which you don't expect; 
        (2) find the code that added the unwanted constraint or constraints and fix it. 
    (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x618000283c00 h=--- v=--- UIWindow:0x7fcf29538cd0.height == 0   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x618000285280 h=-&- v=-&- UITransitionView:0x7fcf294448f0.height == UIWindow:0x7fcf29538cd0.height   (active)>",
    "<NSLayoutConstraint:0x6180002841a0 _UIAlertControllerView:0x7fcf2943bdf0.bottom == UITransitionView:0x7fcf294448f0.bottom - 10   (active)>",
    "<NSLayoutConstraint:0x6180002841f0 V:|-(>=10)-[_UIAlertControllerView:0x7fcf2943bdf0]   (active, names: '|':UITransitionView:0x7fcf294448f0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6180002841a0 _UIAlertControllerView:0x7fcf2943bdf0.bottom == UITransitionView:0x7fcf294448f0.bottom - 10   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

So I started debugging SDK and found where was the problem. It's related with https://github.com/hoko/hoko-ios/commit/27fd888700f89e73e5d6a83c7bc441389453aba8 
line 65: 

```
 -    window.rootViewController = self.safariViewController;
 +    window.rootViewController = rootViewController;
```

If I change it back to use safariViewController everything works like before. I don't know what implications it could have for the whole SDK but my deep links still works.

We ship SDK from pods to our repo so I can make this workaround for now and it will work for us.

Could check this out?

Thanks,
MP.

**Comment by hugocore** [comment] 2016-10-20 11:17
Hi @pawlowskim,

Thanks for pointing that out.

We will review this issue as soon as possible and push a new version that solves this and other minor issues found so far.

**Comment by nelanelanela** [comment] 2016-11-21 12:49
I also found this breaks Facebook Login via SFSafariViewController, VC opens, but the URL is not loaded. Did the fix @pawlowskim suggested and it works fine.

**Comment by alaa001** [comment] 2016-11-22 05:47
@nelanelanela It breaks facebook and Google signin also, It took me sometime to know that this library was the cause of this. 
I never thought it create another UIWindow  with SFSafariViewController in it and make UIWindow alpha 0

http://stackoverflow.com/questions/39019352/ios10-sfsafariviewcontroller-not-working-when-alpha-is-set-to-0

I tried the @pawlowskim  fix but still no use. I hope it will be fixed soon

**Comment by pawlowskim** [comment] 2016-11-22 07:28
I changed a little bit it again. Added version check for iOS.
```
-(void)requestDeferredDeeplink:(void (^)(NSString *))handler {
    BOOL isFirstRun = ![[HOKUtils objectForKey:HOKDeferredDeeplinkingNotFirstRun] boolValue];
    if (isFirstRun) {
        self.handler = handler;
        
#if defined(__IPHONE_OS_VERSION_MAX_ALLOWED) && __IPHONE_OS_VERSION_MAX_ALLOWED >= 90000
        if (HOKSystemVersionGreaterThanOrEqualTo(@"10.0")) {
            NSString *fingerprintURL = [NSString stringWithFormat:@"%@?uid=%@", [HOKNetworkOperation urlFromPath:HOKFingerprintMatchingPath], [HOKDevice device].uid];
            self.safariViewController = [[SFSafariViewController alloc] initWithURL:[NSURL URLWithString:fingerprintURL]];
            self.safariViewController.delegate = self;
            
            UIViewController *rootViewController = [[UIViewController alloc] init];
            
            UIWindow *window = [[UIWindow alloc] initWithFrame:CGRectZero];
            // window.rootViewController = rootViewController;
            //Temporary workaround to make action sheet working. Issue in hoko SDK: https://github.com/hoko/hoko-ios/issues/28
            window.rootViewController = self.safariViewController;
            [window makeKeyAndVisible];
            window.alpha = 0;
            
            [rootViewController presentViewController:self.safariViewController animated:NO completion:nil];
        } else if (HOKSystemVersionGreaterThanOrEqualTo(@"9.0")) {
            NSString *fingerprintURL = [NSString stringWithFormat:@"%@?uid=%@", [HOKNetworkOperation urlFromPath:HOKFingerprintMatchingPath], [HOKDevice device].uid];
            self.safariViewController = [[SFSafariViewController alloc] initWithURL:[NSURL URLWithString:fingerprintURL]];
            self.safariViewController.delegate = self;
            
            UIViewController *rootViewController = [[UIViewController alloc] init];
            
            UIWindow *window = [[UIWindow alloc] initWithFrame:CGRectZero];
            window.rootViewController = rootViewController;
            [window makeKeyAndVisible];
            window.alpha = 0;
            
            [rootViewController presentViewController:self.safariViewController animated:NO completion:nil];
        } else {
            [self requestDeferredDeeplink];
        }
#else
        [self requestDeferredDeeplink];
#endif
    }
}
```

**Comment by hugocore** [comment] 2016-11-22 17:17
Hi guys,

Thank you for reporting this issue. Can you help us out here and check if the bugfix at #30 fixes it?

Remove our pod, and link the source code present at this branch instead:
1. Edit your `Podfile` and remove the `pod 'Hoko'` line
2. Run `pod update` to update your local pod repository
3. Open your Xcode project and link the SDK source code (it should be a drag-drop thing)

Run your app with this version and check if the issue is not longer present. Also, test if your smart links and deferred smart links (those that drive the user through the app store) continue to work.

To test deferred smart links, uninstall your app and then just deploy/install your app through Xcode, once you reach the App Store.

Let us know how it goes.

**Comment by hugocore** [comment] 2016-11-25 14:29
Hi again,

We've release v2.5.0 which includes a fix for this issue.
Please update your local pod.

Best regards,
Hugo

**Closed as completed by hugocore** 2016-11-25 14:29 UTC
Labels: bug
